// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWQNSC1k39eyovMITLz40bNomFROqM11E',
    appId: '1:70539957511:web:b0ca5af8ace73842dde1a2',
    messagingSenderId: '70539957511',
    projectId: 'qc-parts-check',
    authDomain: 'qc-parts-check.firebaseapp.com',
    storageBucket: 'qc-parts-check.appspot.com',
    measurementId: 'G-XBMC8BH3HD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqbZSXFzUGmmsh6Js3KEZ02PZQJn61XHo',
    appId: '1:70539957511:android:752953331a9a31fcdde1a2',
    messagingSenderId: '70539957511',
    projectId: 'qc-parts-check',
    storageBucket: 'qc-parts-check.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_6gdaJmsSXhUshfYHwbFsIWMdbY4Q3LQ',
    appId: '1:70539957511:ios:2685a9528e1eb270dde1a2',
    messagingSenderId: '70539957511',
    projectId: 'qc-parts-check',
    storageBucket: 'qc-parts-check.appspot.com',
    iosClientId: '70539957511-2u2vd08emav1nv31klf17dbbcir1j5fo.apps.googleusercontent.com',
    iosBundleId: 'com.krisnadwia.qcPartsCheck',
  );
}
